### PR TITLE
Feature/ghactions

### PR DESCRIPTION
**Pull request by nsoblath**

### CODE REVIEW

**Comment by nsoblath** [comment]
Known problem: branch==*.build workflow trigger is not working

**Comment by nsoblath** [comment]
Ok, this is finally in a state that's ready to review.  The caveat from above still applies (*.build does not trigger run_tests).  But the rest is working.

**Comment by laroque** [comment]
Why does the publish workflow include the tests that are also in the test workflow? I'd have thought you'd define the workflows each once and then reuse them on different triggers as needed.

**Comment by nsoblath** [comment]
I agree that that's the way it should be, but as far as I can tell, Actions doesn't easily allow that right now.  I found a number of Issues and other threads requesting this sort of feature, and CircleCI was frequently cited as a service with this sort of feature built in.  

The best alternative would have been to keep everything in one workflow file and include a bunch of logic to control which jobs were run under different conditions.  That seemed more delicate to work out correctly.  On the other hand, of course, this option is less convenient for future development because of the duplication.  In the end I went with duplication over complicated logic.

**Review by laroque — APPROVED** [review]
In that case I think it makes sense to just go with it for now. My impression is that github is still working on growing these capabilities and trying to make themselves into a complete platform... it may be that if we wait 6 months they'll just deliver what we want.

**Comment by nsoblath** [comment]
Agreed.  Thanks!

**Pull request closed without merging**
